name: .NET Console CI

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify .NET
        run: dotnet --version

      - name: Restore packages
        run: dotnet restore ./dotnet-demo/dotnet-demo.csproj

      - name: Build application
        run: dotnet build ./dotnet-demo/dotnet-demo.csproj --configuration Release --no-restore

      - name: Run Application
        run: dotnet run --project ./dotnet-demo/dotnet-demo.csproj
