name: .NET Console CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify .NET
        run: dotnet --version

      - name: Restore packages
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run Application
        run: dotnet run

      - name: Post Setup .NET
        run: echo "Build completed successfully!"
